AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to provision EC2 and FindItNow React app'

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.small
  SSHLocation:
    Description: The IP address range that can SSH to the EC2 instance
    Type: String
    Default: 0.0.0.0/0

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: a2_keys
      ImageId: ami-0ba9883b710b05ac6
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install nginx -y
          sudo systemctl enable nginx

          sudo yum install -y nodejs
          
          cd /usr/share/nginx/html
          sudo rm -rf *
          sudo curl -o finditnow.zip https://finditnow-sourcecode.s3.amazonaws.com/finditnow.zip
          sudo unzip finditnow.zip

          sudo npm install
          sudo npm run build

          sudo sed -i 's|root\s\+/usr/share/nginx/html;|root /usr/share/nginx/html/dist;|' /etc/nginx/nginx.conf
          sudo service nginx restart
          

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access and HTTP from the internet
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'SSHLocation'
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

Outputs:
  WebsiteURL:
    Description: URL for website hosted on EC2
    Value: !Sub http://${EC2Instance.PublicDnsName}